/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import dao.TaiKhoan_DAO;

/**
 *
 * @author CHAU
 */
public class GUI_LayLaiMatKhau extends javax.swing.JFrame implements ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form GUI_LayLaiMatKhau
	 */
	public GUI_LayLaiMatKhau() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextField5 = new javax.swing.JTextField();
		pLayLaiMatKhau = new javax.swing.JPanel();
		lblTieuDe = new javax.swing.JLabel();
		btnXacNhan = new javax.swing.JButton();
		btnHuy = new javax.swing.JButton();
		lblTenDangNhapp = new javax.swing.JLabel();
		txtTenDangNhap = new javax.swing.JTextField();
		lblCMND = new javax.swing.JLabel();
		lblSoDienThoai = new javax.swing.JLabel();
		txtCMND = new javax.swing.JTextField();
		lblMatKhauMoi = new javax.swing.JLabel();
		lblXacNhanMK = new javax.swing.JLabel();
		txtSoDienThoai = new javax.swing.JTextField();
		txtMatKhauMoi = new javax.swing.JPasswordField();
		txtXacNhanMatKhau = new javax.swing.JPasswordField();
		btnXemMatKhauMoi = new javax.swing.JButton();
		btnXemXacNhanMK = new javax.swing.JButton();

		jTextField5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		pLayLaiMatKhau.setBackground(new java.awt.Color(255, 255, 255));

		lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		lblTieuDe.setForeground(new java.awt.Color(43, 124, 210));
		lblTieuDe.setText("LẤY LẠI MẬT KHẨU");

		btnXacNhan.setBackground(new java.awt.Color(43, 124, 210));
		btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
		btnXacNhan.setText("Xác Nhận");

		btnHuy.setBackground(new java.awt.Color(43, 124, 210));
		btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnHuy.setForeground(new java.awt.Color(255, 255, 255));
		btnHuy.setText("Huỷ");
		btnHuy.setBorder(null);

		lblTenDangNhapp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblTenDangNhapp.setText("Tên đăng nhập");

		txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTenDangNhapActionPerformed(evt);
			}
		});

		lblCMND.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblCMND.setText("Số CMND");

		lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblSoDienThoai.setText("Số điện thoại ");

		txtCMND.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtCMNDActionPerformed(evt);
			}
		});

		lblMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMatKhauMoi.setText("Mật khẩu mới");

		lblXacNhanMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblXacNhanMK.setText("Xác nhận mật khẩu");

		txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtSoDienThoaiActionPerformed(evt);
			}
		});

		btnXemMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_eye_30px_1.png"))); // NOI18N
		btnXemMatKhauMoi.setBorder(null);

		btnXemXacNhanMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_eye_30px_1.png"))); // NOI18N
		btnXemXacNhanMK.setBorder(null);

		javax.swing.GroupLayout pLayLaiMatKhauLayout = new javax.swing.GroupLayout(pLayLaiMatKhau);
		pLayLaiMatKhau.setLayout(pLayLaiMatKhauLayout);
		pLayLaiMatKhauLayout.setHorizontalGroup(pLayLaiMatKhauLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pLayLaiMatKhauLayout.createSequentialGroup().addGroup(pLayLaiMatKhauLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pLayLaiMatKhauLayout.createSequentialGroup().addGap(113, 113, 113)
								.addComponent(lblTieuDe))
						.addGroup(pLayLaiMatKhauLayout.createSequentialGroup().addGap(36, 36, 36)
								.addGroup(pLayLaiMatKhauLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
												.addComponent(lblSoDienThoai)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE,
														203, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
												.addGroup(pLayLaiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lblTenDangNhapp).addComponent(lblCMND))
												.addGap(46, 46, 46)
												.addGroup(pLayLaiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(txtCMND,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtTenDangNhap,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGroup(pLayLaiMatKhauLayout.createSequentialGroup().addGap(34, 34, 34)
								.addGroup(pLayLaiMatKhauLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
												.addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 116,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(8, 8, 8))
										.addComponent(lblXacNhanMK)
										.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
												.addComponent(lblMatKhauMoi).addGap(44, 44, 44)))
								.addGroup(pLayLaiMatKhauLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pLayLaiMatKhauLayout.createSequentialGroup().addGap(33, 33, 33)
												.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(pLayLaiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
																.addComponent(txtXacNhanMatKhau,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btnXemXacNhanMK))
														.addGroup(pLayLaiMatKhauLayout.createSequentialGroup()
																.addComponent(txtMatKhauMoi,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 203,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btnXemMatKhauMoi)))))))
						.addContainerGap(16, Short.MAX_VALUE)));
		pLayLaiMatKhauLayout.setVerticalGroup(pLayLaiMatKhauLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pLayLaiMatKhauLayout.createSequentialGroup().addGap(31, 31, 31).addComponent(lblTieuDe)
						.addGap(41, 41, 41)
						.addGroup(pLayLaiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTenDangNhapp, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(38, 38, 38)
						.addGroup(pLayLaiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(40, 40, 40)
						.addGroup(pLayLaiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblSoDienThoai))
						.addGap(36, 36, 36)
						.addGroup(pLayLaiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblMatKhauMoi)
								.addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXemMatKhauMoi))
						.addGap(52, 52, 52)
						.addGroup(pLayLaiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblXacNhanMK)
								.addComponent(txtXacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXemXacNhanMK))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
						.addGroup(pLayLaiMatKhauLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
								.addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(54, 54, 54)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pLayLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pLayLaiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
		btnXemMatKhauMoi.addActionListener(this);
		btnXemXacNhanMK.addActionListener(this);
		btnHuy.addActionListener(this);
		btnXacNhan.addActionListener(this);
	}// </editor-fold>//GEN-END:initComponents

	private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTenDangNhapActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtTenDangNhapActionPerformed

	private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCMNDActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtCMNDActionPerformed

	private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSoDienThoaiActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtSoDienThoaiActionPerformed

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI_LayLaiMatKhau().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnHuy;
	private javax.swing.JButton btnXacNhan;
	private javax.swing.JButton btnXemMatKhauMoi;
	private javax.swing.JButton btnXemXacNhanMK;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JLabel lblCMND;
	private javax.swing.JLabel lblMatKhauMoi;
	private javax.swing.JLabel lblSoDienThoai;
	private javax.swing.JLabel lblTenDangNhapp;
	private javax.swing.JLabel lblTieuDe;
	private javax.swing.JLabel lblXacNhanMK;
	private javax.swing.JPanel pLayLaiMatKhau;
	private javax.swing.JTextField txtCMND;
	private javax.swing.JPasswordField txtMatKhauMoi;
	private javax.swing.JTextField txtSoDienThoai;
	private javax.swing.JTextField txtTenDangNhap;
	private javax.swing.JPasswordField txtXacNhanMatKhau;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if (o.equals(btnXemMatKhauMoi)) {
			txtMatKhauMoi.setEchoChar((char) 0);

		} else if (o.equals(btnXemXacNhanMK)) {
			txtXacNhanMatKhau.setEchoChar((char) 0);

		} else if (o.equals(btnXacNhan)) {
			TaiKhoan_DAO tk_DAO = new TaiKhoan_DAO();

			if (txtMatKhauMoi.getPassword().length == 0) // Checking for empty field
				JOptionPane.showMessageDialog(null, "Vui lòng nhập Mật Khẩu  ");
			else if (txtXacNhanMatKhau.getPassword().length == 0) // Checking for empty field
				JOptionPane.showMessageDialog(null, "Vui lòng nhập xác nhận Mật Khẩu mới");
			else if (txtTenDangNhap.getText().toString().length() == 0) { // Checking for empty field
				JOptionPane.showMessageDialog(null, "Vui lòng nhập Tên Đăng Nhập");
			} else if (txtCMND.getText().toString().length() == 0) // Checking for empty field

				JOptionPane.showMessageDialog(null, "Vui lòng nhập CMND");

			else if (txtSoDienThoai.getText().toString().length() == 0) // Checking for empty field

				JOptionPane.showMessageDialog(null, "Vui lòng nhập SDT");

			else {
				char[] passCon = txtXacNhanMatKhau.getPassword(); // Collecting the input
				char[] passNew = txtMatKhauMoi.getPassword(); // Collecting the input
				String pwdNew = String.copyValueOf(passNew);
				String pwdCon = String.copyValueOf(passCon);
				if (pwdNew.equals(pwdCon)) {
					tk_DAO.layMK(txtTenDangNhap.getText().toString(), pwdCon);
					JOptionPane.showMessageDialog(this, "Đặt lại mật khẩu thành công");

				} else
					JOptionPane.showMessageDialog(this, "Xác nhận Mật Khẩu sai");
			}
		} else if (o.equals(btnHuy)) {
			this.dispose();
		}

	}
}
