/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;

import dao.TaiKhoan_DAO;

/**
 *
 * @author CHAU
 */
public class GUI_DangNhap extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form GUILogin
	 */
	public GUI_DangNhap() {
		initComponents();
	}

	public void close() {
		WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
		Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pDangNhap = new javax.swing.JPanel();
		pLeft = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		pRight = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		passMatKhau = new javax.swing.JPasswordField();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		txtTenDangNhap = new javax.swing.JTextField();
		btnDangNhap = new javax.swing.JButton();
		btnQuenMatKhau = new javax.swing.JButton();
		lblTenDangNhap = new javax.swing.JLabel();
		lblMatKhau = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setLocationByPlatform(true);
		setResizable(false);

		pLeft.setBackground(new java.awt.Color(255, 255, 255));

		jLabel3.setBackground(new java.awt.Color(43, 124, 210));
		jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(43, 124, 210));
		jLabel3.setText("CÔNG TY GIÀY DÉP ABC");

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sneaker.png"))); // NOI18N

		javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
		pLeft.setLayout(pLeftLayout);
		pLeftLayout.setHorizontalGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pLeftLayout.createSequentialGroup().addGroup(pLeftLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pLeftLayout.createSequentialGroup().addGap(56, 56, 56).addComponent(jLabel3,
								javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pLeftLayout.createSequentialGroup().addGap(101, 101, 101).addComponent(jLabel4)))
						.addContainerGap(37, Short.MAX_VALUE)));
		pLeftLayout.setVerticalGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLeftLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3,
								javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(101, 101, 101)));

		pRight.setBackground(new java.awt.Color(43, 124, 210));

		jPanel1.setBackground(new java.awt.Color(43, 124, 210));

		passMatKhau.setBackground(new java.awt.Color(43, 124, 210));
		passMatKhau.setForeground(new java.awt.Color(255, 255, 255));
		passMatKhau.setText("1234");
		passMatKhau.setBorder(null);
		passMatKhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passMatKhauActionPerformed(evt);
			}
		});

		jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
		jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
		jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

		jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
		jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
		jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

		txtTenDangNhap.setBackground(new java.awt.Color(43, 124, 210));
		txtTenDangNhap.setForeground(new java.awt.Color(255, 255, 255));
		txtTenDangNhap.setText("ADMIN");
		txtTenDangNhap.setBorder(null);
		txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTenDangNhapActionPerformed(evt);
			}
		});

		btnDangNhap.setBackground(new java.awt.Color(0, 204, 255));
		btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
		btnDangNhap.setText("Đăng Nhập");
		btnDangNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

		btnQuenMatKhau.setBackground(new java.awt.Color(0, 204, 255));
		btnQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
		btnQuenMatKhau.setText("Quên mật khẩu");
		btnQuenMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuenMatKhauActionPerformed(evt);
			}
		});

		lblTenDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_person_20px.png"))); // NOI18N

		lblMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_lock_20px.png"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(31, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lblMatKhau, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 21,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblTenDangNhap, javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(passMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE,
														233, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(37, 37, 37))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(btnQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(15, 15, 15)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap(9, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblTenDangNhap))
								.addGap(9, 9, 9)
								.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(passMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblMatKhau))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(35, 35, 35)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
												javax.swing.GroupLayout.PREFERRED_SIZE))));

		javax.swing.GroupLayout pRightLayout = new javax.swing.GroupLayout(pRight);
		pRight.setLayout(pRightLayout);
		pRightLayout.setHorizontalGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pRightLayout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		pRightLayout.setVerticalGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pRightLayout.createSequentialGroup().addGap(70, 70, 70)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(77, Short.MAX_VALUE)));

		javax.swing.GroupLayout pDangNhapLayout = new javax.swing.GroupLayout(pDangNhap);
		pDangNhap.setLayout(pDangNhapLayout);
		pDangNhapLayout
				.setHorizontalGroup(pDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pDangNhapLayout.createSequentialGroup()
								.addComponent(pLeft, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(pRight, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		pDangNhapLayout.setVerticalGroup(pDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(pLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(pRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(pDangNhap,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
		btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDangNhap(evt);
            }
        });
		btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnQuenMatKhauActionPerformed(evt);
            }
        });
	}// </editor-fold>//GEN-END:initComponents

	private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTenDangNhapActionPerformed
	}// GEN-LAST:event_txtTenDangNhapActionPerformed

	private void passMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passMatKhauActionPerformed
	}// GEN-LAST:event_passMatKhauActionPerformed

	private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuenMatKhauActionPerformed
		GUI_LayLaiMatKhau pi = new GUI_LayLaiMatKhau();
		pi.setVisible(true);
	}// GEN-LAST:event_btnQuenMatKhauActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new splashscreen.SplashScreen(null, true).setVisible(true);
			
				new GUI_DangNhap().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDangNhap;
	private javax.swing.JButton btnQuenMatKhau;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JLabel lblMatKhau;
	private javax.swing.JLabel lblTenDangNhap;
	private javax.swing.JPanel pDangNhap;
	private javax.swing.JPanel pLeft;
	private javax.swing.JPanel pRight;
	private javax.swing.JPasswordField passMatKhau;
	private javax.swing.JTextField txtTenDangNhap;
	public static String role;
	// End of variables declaration//GEN-END:variables
	
	private void btnDangNhap(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		TaiKhoan_DAO tk_DAO = new TaiKhoan_DAO();
		role = txtTenDangNhap.getText().toString();
		System.out.println(role);
		if (txtTenDangNhap.getText().length() == 0) // Checking for empty field
			JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
		else if (passMatKhau.getPassword().length == 0) // Checking for empty field
			JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
		else {
			String user = txtTenDangNhap.getText(); // Collecting the input
			char[] pass = passMatKhau.getPassword(); // Collecting the input
			String pwd = String.copyValueOf(pass); // converting from array to string
			if (tk_DAO.login(user, pwd)) {
				JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
				this.dispose();
				
				new GUI().setVisible(true);
			} else {
				JOptionPane.showMessageDialog(null, "Sai thông tin đăng nhập");
			}

		}
		
	}
	public String getRole() {
		return role;
	}
	
	
	
}
