/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import dao.TaiKhoan_DAO;

/**
 *
 * @author CHAU
 */
public class GUI_DoiMatKhau extends javax.swing.JFrame implements ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form GUIDoiMatKhau
	 */
	public GUI_DoiMatKhau() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pDoiMatKhau = new javax.swing.JPanel();
		lblTieuDe = new javax.swing.JLabel();
		btnXacNhan = new javax.swing.JButton();
		btnHuy = new javax.swing.JButton();
		lbMatKhauCu = new javax.swing.JLabel();
		lblMatKhauMoi = new javax.swing.JLabel();
		lblXacNhanMKMoi = new javax.swing.JLabel();
		txtMatKhauCu = new javax.swing.JPasswordField();
		txtMatKhauMoi = new javax.swing.JPasswordField();
		txtXacNhanMKMoi = new javax.swing.JPasswordField();
		btnXemMKCu = new javax.swing.JButton();
		btnXemMKMoi = new javax.swing.JButton();
		btnXemXacNhanMK = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		pDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));

		lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		lblTieuDe.setForeground(new java.awt.Color(43, 124, 210));
		lblTieuDe.setText("ĐỔI MẬT KHẨU");

		btnXacNhan.setBackground(new java.awt.Color(43, 124, 210));
		btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
		btnXacNhan.setText("Xác Nhận");

		btnHuy.setBackground(new java.awt.Color(43, 124, 210));
		btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		btnHuy.setForeground(new java.awt.Color(255, 255, 255));
		btnHuy.setText("Huỷ");
		btnHuy.setBorder(null);

		lbMatKhauCu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lbMatKhauCu.setText("Mật khẩu cũ");

		lblMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblMatKhauMoi.setText("Mật khẩu mới");

		lblXacNhanMKMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		lblXacNhanMKMoi.setText("Xác nhận mật khẩu");

		txtMatKhauCu.setText("jPasswordField1");

		txtMatKhauMoi.setText("jPasswordField1");

		txtXacNhanMKMoi.setText("jPasswordField1");

		btnXemMKCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_eye_30px_1.png"))); // NOI18N
		btnXemMKCu.setBorder(null);

		btnXemMKMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_eye_30px_1.png"))); // NOI18N
		btnXemMKMoi.setBorder(null);

		btnXemXacNhanMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_eye_30px_1.png"))); // NOI18N
		btnXemXacNhanMK.setBorder(null);

		javax.swing.GroupLayout pDoiMatKhauLayout = new javax.swing.GroupLayout(pDoiMatKhau);
		pDoiMatKhau.setLayout(pDoiMatKhauLayout);
		pDoiMatKhauLayout.setHorizontalGroup(pDoiMatKhauLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pDoiMatKhauLayout.createSequentialGroup().addGroup(pDoiMatKhauLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pDoiMatKhauLayout.createSequentialGroup().addGap(58, 58, 58)
								.addGroup(pDoiMatKhauLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(pDoiMatKhauLayout.createSequentialGroup()
												.addComponent(lblXacNhanMKMoi)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(txtXacNhanMKMoi, javax.swing.GroupLayout.DEFAULT_SIZE,
														176, Short.MAX_VALUE))
										.addGroup(pDoiMatKhauLayout.createSequentialGroup()
												.addGroup(pDoiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lbMatKhauCu).addComponent(lblMatKhauMoi))
												.addGap(54, 54, 54)
												.addGroup(pDoiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(txtMatKhauCu,
																javax.swing.GroupLayout.DEFAULT_SIZE, 176,
																Short.MAX_VALUE)
														.addComponent(txtMatKhauMoi))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
										pDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnXemMKCu).addComponent(btnXemMKMoi)
												.addComponent(btnXemXacNhanMK)))
						.addGroup(
								pDoiMatKhauLayout.createSequentialGroup().addGap(164, 164, 164).addComponent(lblTieuDe))
						.addGroup(
								pDoiMatKhauLayout.createSequentialGroup().addGap(123, 123, 123).addComponent(btnXacNhan)
										.addGap(57, 57, 57).addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE,
												87, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(70, Short.MAX_VALUE)));
		pDoiMatKhauLayout.setVerticalGroup(pDoiMatKhauLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pDoiMatKhauLayout.createSequentialGroup().addGap(28, 28, 28).addComponent(lblTieuDe)
						.addGap(26, 26, 26)
						.addGroup(pDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(pDoiMatKhauLayout.createSequentialGroup().addGroup(pDoiMatKhauLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(pDoiMatKhauLayout.createSequentialGroup().addGroup(pDoiMatKhauLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(pDoiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lbMatKhauCu,
																javax.swing.GroupLayout.PREFERRED_SIZE, 25,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtMatKhauCu,
																javax.swing.GroupLayout.PREFERRED_SIZE, 34,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(btnXemMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(53, 53, 53)
												.addGroup(pDoiMatKhauLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblMatKhauMoi,
																javax.swing.GroupLayout.PREFERRED_SIZE, 25,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtMatKhauMoi,
																javax.swing.GroupLayout.PREFERRED_SIZE, 34,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(btnXemMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(pDoiMatKhauLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblXacNhanMKMoi).addComponent(txtXacNhanMKMoi,
														javax.swing.GroupLayout.PREFERRED_SIZE, 35,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(btnXemXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(37, 37, 37)
						.addGroup(pDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnXacNhan).addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE,
										31, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(46, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
		btnXemMKCu.addActionListener(this);
		btnXemMKMoi.addActionListener(this);
		btnXemXacNhanMK.addActionListener(this);
		btnXacNhan.addActionListener(this);
		btnHuy.addActionListener(this);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI_DoiMatKhau().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnHuy;
	private javax.swing.JButton btnXacNhan;
	private javax.swing.JButton btnXemMKCu;
	private javax.swing.JButton btnXemMKMoi;
	private javax.swing.JButton btnXemXacNhanMK;
	private javax.swing.JLabel lbMatKhauCu;
	private javax.swing.JLabel lblMatKhauMoi;
	private javax.swing.JLabel lblTieuDe;
	private javax.swing.JLabel lblXacNhanMKMoi;
	private javax.swing.JPanel pDoiMatKhau;
	private javax.swing.JPasswordField txtMatKhauCu;
	private javax.swing.JPasswordField txtMatKhauMoi;
	private javax.swing.JPasswordField txtXacNhanMKMoi;
	private GUI_DangNhap dn_GUI;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if (o.equals(btnXemMKCu)) {
			txtMatKhauCu.setEchoChar((char) 0);
		} else if (o.equals(btnXemMKMoi)) {
			txtMatKhauMoi.setEchoChar((char) 0);
		} else if (o.equals(btnXemXacNhanMK)) {
			txtXacNhanMKMoi.setEchoChar((char) 0);
		} else if (o.equals(btnXacNhan)) {
			TaiKhoan_DAO tk_DAO = new TaiKhoan_DAO();
			dn_GUI = new GUI_DangNhap();

			if (txtMatKhauCu.getPassword().length == 0) // Checking for empty field
				JOptionPane.showMessageDialog(null, "Vui lòng nhập Mật Khẩu cũ ");
			else if (txtMatKhauMoi.getPassword().length == 0) // Checking for empty field
				JOptionPane.showMessageDialog(null, "Vui lòng nhập Mật Khẩu mới");
			else if (txtXacNhanMKMoi.getPassword().length == 0) // Checking for empty field
				JOptionPane.showMessageDialog(null, "Vui lòng nhập xác nhận Mật Khẩu mới");
			else {
				char[] passCon = txtXacNhanMKMoi.getPassword(); // Collecting the input
				char[] passNew = txtMatKhauMoi.getPassword(); // Collecting the input
				char[] passOld = txtMatKhauCu.getPassword(); // Collecting the input
				String pwd = String.copyValueOf(passOld);
				String pwdNew = String.copyValueOf(passNew);
				String pwdCon = String.copyValueOf(passCon);

				if (pwd.equalsIgnoreCase(tk_DAO.getMK(dn_GUI.getRole()))) {
					if (pwdNew.equalsIgnoreCase(pwdCon)) {
						JOptionPane.showMessageDialog(this, "Đỏi Mật Khẩu thành công");
						tk_DAO.doiMK(dn_GUI.getRole(), pwd, pwdNew);
					} else
						JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu sai");
				} else
					JOptionPane.showMessageDialog(this, "Mật khẩu cũ sai");
			}
		}
		else if(o.equals(btnHuy)) {
			this.dispose();
		}
	}
}
